spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Scheduler
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/postgres
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      properties:
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
  task:
    scheduling:
      pool:
        size: 3
server:
  port: 8082
scheduler:
  time-zone: ${SCHEDULED_TIME_ZONE:Europe/Moscow}
